import { toWireString, type Decimal } from '@stockwatch/contracts';
import type { ComparisonStatus } from '../diff/engine.js';

/**
 * Deterministic personal clause (T31, architecture §F.7 — INV-14, INV-9).
 * Always template-generated by the API from values the caller already computed
 * (T27's DiffEngine output) — no arithmetic here, no personal data reaches a model.
 */
export interface PersonalClauseInput {
  readonly comparisonStatus: ComparisonStatus;
  readonly sessionsElapsed?: number;
  readonly percentageChange?: Decimal;
}

export function renderPersonalClause(input: PersonalClauseInput): string {
  switch (input.comparisonStatus) {
    case 'AWAITING_BASELINE':
      return "This is the first time you're seeing this instrument.";
    case 'SUPPRESSED_CORPORATE_ACTION':
      return "An unsupported corporate action means this can't be compared to your last check.";
    case 'OK':
    case 'INSUFFICIENT_HISTORY': {
      const sessions = input.sessionsElapsed ?? 0;
      const sessionWord = sessions === 1 ? 'session' : 'sessions';
      const pct = input.percentageChange !== undefined ? toWireString(input.percentageChange) : '0';
      return `Since you last checked ${sessions} ${sessionWord} ago, it has moved ${pct}.`;
    }
  }
}
