import { toWireString, type Decimal } from '@stockwatch/contracts';
import type { ComparisonStatus } from '../diff/engine.js';

/**
 * Deterministic personal clause (T31, architecture §F.7 — INV-14, INV-9).
 * Always template-generated by the API from values the caller already computed
 * (T27's DiffEngine output) — no arithmetic here, no personal data reaches a model.
 */
export interface PersonalClauseInput {
  readonly comparisonStatus: ComparisonStatus;
  readonly elapsedMs?: number;
  readonly percentageChange?: Decimal;
}

const MS_PER_MINUTE = 60_000;
const MS_PER_HOUR = MS_PER_MINUTE * 60;
const MS_PER_DAY = MS_PER_HOUR * 24;

/**
 * Phrases a millisecond duration already computed by DiffEngine ("elapsedMs" — wall-clock time
 * between the user's baseline and the current observation) into words. Picking a unit and
 * rounding is display phrasing of a value the API owns, not a new calculation.
 */
function phraseDuration(elapsedMs: number): string {
  if (elapsedMs < MS_PER_MINUTE) return 'moments';
  if (elapsedMs < MS_PER_HOUR) {
    const minutes = Math.round(elapsedMs / MS_PER_MINUTE);
    return `${minutes} minute${minutes === 1 ? '' : 's'}`;
  }
  if (elapsedMs < MS_PER_DAY) {
    const hours = Math.round(elapsedMs / MS_PER_HOUR);
    return `${hours} hour${hours === 1 ? '' : 's'}`;
  }
  const days = Math.round(elapsedMs / MS_PER_DAY);
  return `${days} day${days === 1 ? '' : 's'}`;
}

export function renderPersonalClause(input: PersonalClauseInput): string {
  switch (input.comparisonStatus) {
    case 'AWAITING_BASELINE':
      return "This is the first time you're seeing this instrument.";
    case 'SUPPRESSED_CORPORATE_ACTION':
      return "An unsupported corporate action means this can't be compared to your last check.";
    case 'OK':
    case 'INSUFFICIENT_HISTORY': {
      const duration = input.elapsedMs !== undefined ? phraseDuration(input.elapsedMs) : 'moments';
      const pct = input.percentageChange !== undefined ? toWireString(input.percentageChange) : '0';
      // The "%" is a unit label for a figure that already is a percentage (DiffEngine returns
      // percentageChange on the percentage scale), not a conversion — nothing is computed here.
      return `Since you last checked ${duration} ago, it has moved ${pct}%.`;
    }
  }
}
